name = "Radix"
uuid = "91324510-8a80-4dcc-8f77-32500317c0e2"
version = "0.1.0"
authors = ["Paul Barrett <pebarrett@gmail.com>"]

[deps]
FITSFiles = "358a0a88-3548-4ad6-b652-8bdbf64af8e5"

[compat]
FITSFiles = "0.2.0"
julia = "1.9.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
